version: "3.8"
services:
  frontend:
    build: ./frontend
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mern-app

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - mern-app

  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
 
 


